/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author estiven
 */
public class SelectActionScreen extends javax.swing.JPanel {

    MainScreen parentScreen;

    /**
     * Creates new form SelectActionScreem
     *
     * @param mainScreen
     */
    public SelectActionScreen(MainScreen mainScreen) {
        this.parentScreen = mainScreen;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        transferBTN = new javax.swing.JButton();
        loanBTN = new javax.swing.JButton();
        extractionBTN = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        transferBTN.setText("Tranferencia");
        transferBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBTNActionPerformed(evt);
            }
        });

        loanBTN.setText("Prestamo");
        loanBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanBTNActionPerformed(evt);
            }
        });

        extractionBTN.setText("Extracion");
        extractionBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractionBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transferBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extractionBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(transferBTN)
                .addGap(40, 40, 40)
                .addComponent(extractionBTN)
                .addGap(43, 43, 43)
                .addComponent(loanBTN)
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void transferBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBTNActionPerformed
        parentScreen.setScreen("INSERT_CARD");
    }//GEN-LAST:event_transferBTNActionPerformed

    private void loanBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanBTNActionPerformed
        parentScreen.setScreen("INSERT_CARD");
    }//GEN-LAST:event_loanBTNActionPerformed

    private void extractionBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractionBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extractionBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton extractionBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loanBTN;
    private javax.swing.JButton transferBTN;
    // End of variables declaration//GEN-END:variables
}
